---
title: "Gapminder analysis"
author: "[Yan Holtz](https://github.com/holtzy)"
date: "`r format(Sys.time(), '%d %B %Y')`"
mail: "yan.holtz.data@gmail.com"
linkedin: "yan-holtz-2477534a"
twitter: "r_graph_gallery"
github: "holtzy"
home: "www.yan-holtz.com"
# !!! You need to provide a logo image here !!! Or just delete the field for no logo
logo: "logo_gallery.png"
output:
  epuRate::epurate:
    toc: TRUE
    number_sections: FALSE
    code_folding: "show"
---


<br><br>


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Libraries
*** 

Let's load some libraries needed
```{r, warning=FALSE, message=FALSE }
# Libraries
library(tidyverse)   # includes ggplot2
library(hrbrthemes)  # better chart appearance
library(viridis)     # better color palette
library(plotly)      # interactive charts
#library(gridExtra)

# The dataset is provided in the gapminder library
library(gapminder)
```

## Data wrangling
*** 

Let's keep data for 2007 only

```{r}
data <- gapminder %>% filter(year=="2007") %>% select(-year)
```


## Let's build a chart
*** 

Build the chart with ggplot2, make it interactive with plotly.


```{r}
# Interactive version
p <- data %>%
  mutate(gdpPercap=round(gdpPercap,0)) %>%
  mutate(pop=round(pop/1000000,2)) %>%
  mutate(lifeExp=round(lifeExp,1)) %>%
  arrange(desc(pop)) %>%
  mutate(country = factor(country, country)) %>%
  mutate(text = paste("Country: ", country, "\nPopulation (M): ", pop, "\nLife Expectancy: ", lifeExp, "\nGdp per capita: ", gdpPercap, sep="")) %>%
  ggplot( aes(x=gdpPercap, y=lifeExp, size = pop, color = continent, text=text)) +
    geom_point(alpha=0.7) +
    scale_size(range = c(1.4, 19), name="Population (M)") +
    scale_color_viridis(discrete=TRUE, guide=FALSE) +
    theme_ipsum() +
    theme(legend.position="none")

ggplotly(p, tooltip="text")
````